apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsubnets.ec2.aws.signavio.cloud
spec:
  group: ec2.aws.signavio.cloud
  names:
    kind: XSubnet
    plural: xsubnets
  claimNames:
    kind: CSubnet
    plural: csubnets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigRef:
                  description: Specifies how the provider creates, observes, updates, and deletes resources.
                  type: object
                  properties:
                    terraform:
                      description: Provider name for Terraform required to get VPC information
                      type: string
                    aws:
                      description: Provider name for AWS
                      type: string
                availabilityZone:
                  description: Availability Zone of Subnet
                  type: string
                  enum:
                    - a
                    - b
                    - c
                    - d
                subnetType:
                  description: Type of subnet
                  type: string
                  enum:
                    - Private
                    - Public
                    - Isolated
                overrideMetadataName:
                  description: |
                    Use the claim name as metadata.name to enforce static name of generated resource.
                    Only used for testing.
                  type: string
              required:
                - availabilityZone
                - subnetType
            status:
              description: A Status represents the observed state
              properties:
                availabilityZone:
                  description: Availability Zone of Subnet
                  type: string
                subnetId:
                  description: Subnet ID
                  type: string
                vpcId:
                  description: VPC ID
                  type: string
                subnetType:
                  description: Type of subnet
                  type: string
                subnetTags:
                  additionalProperties:
                    type: string
                  description: Key-value map of resource tags.
                  type: object
              type: object
